{{- if and .Values.requestManagement.agentService.configPersistence.enabled (not .Values.requestManagement.agentService.configPersistence.existingClaim) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "self-service-agent.fullname" . }}-agent-service-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent-service
spec:
  accessModes:
    {{- toYaml .Values.requestManagement.agentService.configPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.requestManagement.agentService.configPersistence.size | quote }}
  {{- if .Values.requestManagement.agentService.configPersistence.storageClassName }}
  storageClassName: {{ .Values.requestManagement.agentService.configPersistence.storageClassName | quote }}
  {{- end }}
{{- end }}

