{{- if .Values.pgvectorSecret }}
{{- if (.Values.pgvectorSecret.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgvectorSecret.name | default "pgvector" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.pgvectorSecret.host | default "" | quote }}
  port: {{ .Values.pgvectorSecret.port | default "5432" | quote }}
  dbname: {{ .Values.pgvectorSecret.dbname | default "postgres" | quote }}
  user: {{ .Values.pgvectorSecret.user | default "" | quote }}
  password: {{ .Values.pgvectorSecret.password | default "" | quote }}
{{- end }}
{{- end }}
