{{- if .Values.servicenowCredentials }}
{{- if (.Values.servicenowCredentials.create | default false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "self-service-agent.fullname" . }}-servicenow-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "self-service-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  servicenow-instance-url: {{ .Values.servicenowCredentials.instanceUrl | default "" | quote }}
  servicenow-api-key: {{ .Values.servicenowCredentials.apiKey | default "" | quote }}
{{- end }}
{{- end }}
