apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: it-self-service-agent

commonLabels:
  app: self-service-agent
  component: webclient

resources:
  - imagestream.yaml
  - buildconfig.yaml
