apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: it-self-service-agent

commonLabels:
  app: self-service-agent
  component: webclient

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/it-self-service-agent/webclient
    newTag: latest
